version: "3"

tasks:
  default:
    cmds:
      - task: build
  test:
    cmds:
      - go run gotest.tools/gotestsum@v1.11.0
  linters:
    cmds:
      - golangci-lint run
  build:
    generates:
      - bin/stencil
    sources:
      - "./**/*.go"
      - .tool-versions # Trigger rebuild on Go version changes.
    cmds:
      - go build -trimpath -o ./bin/ -v ./cmd/stencil
