name: docs

on:
  push:
    branches:
      - main

concurrency:
  group: stencil-docs-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for lastUpdated
      - uses: jdx/mise-action@v2
        with:
          experimental: true
        env:
          GH_TOKEN: ${{ github.token }}
      - run: bun install
        working-directory: docs
      - run: bun run docs:build
        working-directory: docs
      - run: .mise/tasks/release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: docs
