name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Retrieve golangci-lint version
        run: |
          echo "version=$(rtx current golangci-lint)" >> "$GITHUB_OUTPUT"
        id: golangci_lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ steps.golangci_lint.outputs.version }}
          args: --timeout=30m
